import { Inter } from "next/font/google";
import "./globals.css";
import MainFooter from "../components/MainFooter";
import CTA from "../components/CTA";
import Nav from "../components/Nav.jsx";




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">

      <body className={inter.className}>
        <Nav/>
        {children}
        <footer>     
          <CTA/>
          <MainFooter/>
        </footer>
      </body>

    </html>
  );
}
