import { Inter } from "next/font/google";
import "./globals.css";
import MainFooter from "../components/MainFooter";
import CTA from "../components/CTA";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <CTA/>
      <footer>
        <MainFooter/>
      </footer>
    </html>
  );
}
